apiVersion: 1

policies:
  - orgId: 1
    receiver: Webhook
    group_by: ['alertname', 'cluster', 'service']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: Discord
        matchers:
          - severity =~ "critical|warning"
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        continue: true
      - receiver: Email
        matchers:
          - severity = critical
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        continue: true
